name: Simple Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        if: github.ref == 'refs/head/main'
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Save Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}
      - uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: dist/
        